### PR TITLE
Lw query improvements

### PR DESCRIPTION
**Pull request by webberlh**
A few more changes to speed up the query CLI.
- Use `FILE` API for writing out results rather than `stream` API.
- Use `logger.format` for formatting floats as it outperforms 'printf'.
- Presize vectors where possible when reading out values.

A few other things I tried that didn't have much of an impact on performance in the particular case I was using for testing, included here for reference:
- Replacing the output `FILE*` with either a `mmap`'ed file or a `fmemopen`'ed buffer. Neither altered the results much.
- Separate reader/writer threads. I was able to get the multi-threaded approach equal in performance using `atomic`'s, but wasn't able to surpass the single threaded performance as formatting the floating points would dominate the workload of whatever thread handled it. I think there are still some more avenues to explore here, maybe using a thread pool to get the work off the worker threads entirely.

### CODE REVIEW

**Review by nalinigans — COMMENTED** [review]
Changes look good. Yes, `fmt` is the way to go for performance when formatting output. How did you benchmark write performance? Was it on NFS? Or local filesystems? Also, if you allow for output files to be specified to the `cli`, we could use TileDB `write_to_file` that uses a kernel write. This would also allow for us to write the output tp the cloud directly. Thoughts?

**Comment by webberlh** [comment]
It was all done with the local filesystem, as a first pass. 

I think having support for direct cloud writing would be nice, my only concern would be to not incur too large a penalty for the local case as a side effect. A quick back of the envelope test on my laptop, the write takes about 25m when using `FileUtility::write_file` to invoke TileDB's `write_to_file`. I still want to test buffering the output better, since it would be preferable to have a unified API for doing writes.

Depending on how my attempts at buffering go, maybe we could have the output file as an optional argument, if it's present the user has opted into the cost and we use `write_to_file` allowing for cloud writes as well, and if it's absent we default back to `stdout` and C style writes?

**Comment by webberlh** [comment]
Buffering the writes seems to bring the performance in-line with my manual invocation of the C API, so I'll go ahead and update this PR.

**Comment by webberlh** [comment]
Changes are in. For this PR, I've left the file as `stdout` and created #54 to track allowing the user to input their desired file. The buffer size is also hard coded at the moment, I've created #55 to track allowing that to be configured.

**Review by nalinigans — APPROVED** [review]
Looks good. A few comments here -
TileDB for Posix has a really good performance as we are invoking the kernel directly. There are [environment variables in TileDB ](https://github.com/OmicsDataAutomation/TileDB/blob/master/core/EnvironmentVariables.md) for buffering, keeping file handles open until the end(the C File does that), disabling file locking(especially useful for NFS), etc. We could make all this first class configuration parameters later, but all these allow for a real fast read/write on Posix based filesystems. Also maybe we should be `requiring` output filename to be specified from the `CLI`.

Let's chat later when I have refactored tiledb array storage out of OmicsDS.

**Pull request merged**
